# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "dev.demo.softshake"
  #config.vm.hostname = "qa.demo.softshake"

  config.vm.box = "centos-6.5-64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box"

  config.vm.synced_folder "../cache", "/cache"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "modules"
    puppet.manifest_file  = "site.pp"
    puppet.options = "--verbose"
  end

#  config.vm.provider "virtualbox" do |v|
#    v.gui = true
#  end  
end
